### ISSUE TITLE
Fix TS build error: Reveal component missing delay prop breaks every PR's build check

### ISSUE THREAD

**Issue by karlwint** [WintCom-Solutions/wintersoperations-site#51]
## Task

`npm run build` (which runs `next build` with typecheck) currently fails on `main` itself, which means the `build` CI check will fail on every open and future PR in this repo until fixed — discovered while investigating an unrelated CI failure on PR #50.

## Verified bug

`app/guides/page.tsx:35` calls:
```tsx
<Reveal key={g.slug} delay={i * 60}>
```
but `components/Reveal.tsx`'s prop type only declares `children` and `className` — no `delay`. This has been broken since `delay` was added in #45 (guides content). Every other `Reveal` call site (`app/page.tsx`, `app/services/page.tsx`, `app/work/page.tsx`) omits `delay` and compiles fine; only `guides/page.tsx` hits this.

Build error:
```
app/guides/page.tsx(35,36): error TS2322: Type '{ children: Element; key: ...; delay: number; }' is not assignable to type 'IntrinsicAttributes & { children: ReactNode; className?: string | undefined; }'.
  Property 'delay' does not exist on type 'IntrinsicAttributes & { children: ReactNode; className?: string | undefined; }'.
```

## Scope

- Add an optional `delay?: number` prop (default `0`) to `components/Reveal.tsx`.
- Apply it as `style={{ transitionDelay: delay ? \`${delay}ms\` : undefined }}` on the component's wrapping `<div>`. `.reveal` / `.reveal.visible` in `app/globals.css:87-93` already use `transition-all duration-700`, so a `transition-delay` produces the per-item staggered reveal `guides/page.tsx` was clearly trying to achieve with `delay={i * 60}`.
- Do not change any other `Reveal` call site or any other component.
- No visible behavior change for the three call sites that don't pass `delay` (default `0` is a no-op).

## Acceptance

- `npm run build` succeeds with no TypeScript errors.
- The guides page renders with a staggered reveal (each card's transition delayed by `index * 60ms`).
- No change to `Reveal`'s behavior anywhere `delay` isn't passed.

## Validation

Run from repo root: `npm run build` (must pass — this is the check currently failing), plus whatever lint/test scripts this repo's CI runs. PR must include `Closes #<this issue>` and validation evidence.

## Out of scope

- Any other Reveal usage or animation behavior change.
- Anything raised in the improvement-proposals tracker (#49) — this is an unrelated, pre-existing, build-breaking bug, not a proposal.
